Update action.yml

diff --git a/.github/actions/fetch-env/action.yml b/.github/actions/fetch-env/action.yml
--- a/.github/actions/fetch-env/action.yml
+++ b/.github/actions/fetch-env/action.yml
@@ -15,28 +15,25 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Configure AWS Credentials
+    - name: Install AWS CLI (if not available)
       run: |
-        export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
-        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
-        export AWS_REGION="${{ inputs.aws-region }}"
-        aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
-        aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
-        aws configure set region "${AWS_REGION}"
+        if ! command -v aws &> /dev/null; then
+          echo "AWS CLI not found, installing..."
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli.zip"
+          unzip awscli.zip
+          sudo ./aws/install
+        fi
       shell: bash
 
-    - name: Get environment variables from AWS SSM
-      uses: eliasjcjunior/aws-ssm-parameters-action@1.2.2
-      with:
-        paths: "/drivers-license-api-staging-env"
-        recursive: true
-        with-decryption: true
-        split-env: true
-        upper-case: false
-        env-prefix: "AWS_"
-
-    - name: Save all parameters to .env file
+    - name: Configure AWS Credentials
       run: |
-        env | grep '^AWS_' | sed 's/^AWS_//' > .env
+        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }}
+        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
+        aws configure set region ${{ inputs.aws-region }}
+      shell: bash
+
+    - name: Pull API environment variables
+      run: |
+        aws ssm get-parameter --name drivers-license-api-staging-env --output text --query Parameter.Value --region ${{ inputs.aws-region }} > .env
         cat .env  # Debugging step to verify contents
       shell: bash
