Update staging-cd.yml

diff --git a/.github/workflows/staging-cd.yml b/.github/workflows/staging-cd.yml
--- a/.github/workflows/staging-cd.yml
+++ b/.github/workflows/staging-cd.yml
@@ -36,16 +36,19 @@ jobs:
           cd VPC
           terraform apply -auto-approve -var-file=stage.tfvars
 
+     
+
       - name: Extract EC2 Public IP from Terraform Output
         id: extract_ip
         run: |
           cd VPC
-          IP=$(terraform output -raw instance_public_ip || true)
+          IP=$(terraform output -raw instance_public_ip 2>/dev/null || echo "")
           if [ -z "$IP" ]; then
-          echo "❌ Failed to get instance_public_ip from Terraform output."
+          echo "Terraform output 'instance_public_ip' not found."
           exit 1
           fi
           echo "EC2_IP=$IP" >> $GITHUB_ENV
+
 
 
     
