Update staging-cd.yml

diff --git a/.github/workflows/staging-cd.yml b/.github/workflows/staging-cd.yml
--- a/.github/workflows/staging-cd.yml
+++ b/.github/workflows/staging-cd.yml
@@ -42,12 +42,14 @@ jobs:
         id: extract_ip
         run: |
           cd VPC
-          IP=$(terraform output -raw instance_public_ip 2>/dev/null || echo "")
-          if [ -z "$IP" ]; then
-          echo "Terraform output 'instance_public_ip' not found."
-          exit 1
+          IP=$(terraform output -raw instance_public_ip 2>&1 || true)
+          echo "Raw Terraform Output: $IP"
+          if [[ "$IP" == *"╷"* || -z "$IP" ]]; then
+            echo "Terraform output 'instance_public_ip' not found or failed."
+             exit 1
           fi
           echo "EC2_IP=$IP" >> $GITHUB_ENV
+
 
 
 
